### ISSUE TITLE
Use Mintaka without internet

### ISSUE THREAD

**Issue by IngMiad** [wistefan/mintaka#136]
Hello,

we have a use case in a security critical environment that has no internet access. I tried to deploy Orion-LD with Mintaka for Short-Term-History Storage there, but I get an error that Mintaka isn't able to download the default context:
```
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v2.4.1)

16:44:29.077 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [org.fiware.mintaka.context.$LdContextCacheDefinition$Intercepted] could not be loaded: Error instantiating bean of type [org.fiware.mintaka.context.$LdContextCacheDefinition$Intercepted]: Invalid core context configured.
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [org.fiware.mintaka.context.$LdContextCacheDefinition$Intercepted] could not be loaded: Error instantiating bean of type [org.fiware.mintaka.context.$LdContextCacheDefinition$Intercepted]: Invalid core context configured.
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1565)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:219)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2857)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:231)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:165)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:311)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
	at org.fiware.mintaka.Application.main(Application.java:29)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [org.fiware.mintaka.context.$LdContextCacheDefinition$Intercepted]: Invalid core context configured.
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1972)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2724)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2260)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1559)
	... 8 common frames omitted
Caused by: org.fiware.mintaka.exception.ContextRetrievalException: Invalid core context configured.
	at org.fiware.mintaka.context.LdContextCache.initDefaultContext(LdContextCache.java:55)
	at org.fiware.mintaka.context.$$LdContextCacheDefinition$InterceptedDefinition.initialize(Unknown Source)
	at org.fiware.mintaka.context.$$LdContextCacheDefinition$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1943)
	... 11 common frames omitted
Caused by: java.net.UnknownHostException: uri.etsi.org
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at com.github.jsonldjava.utils.JsonUtils.fromURLJavaNet(JsonUtils.java:432)
	at org.fiware.mintaka.context.LdContextCache.initDefaultContext(LdContextCache.java:53)
	... 14 common frames omitted
```

Can I use Mintaka without internet somehow or will it always try to download the default context from a public URL? 

Greetings
Inga

**Comment by wistefan** [comment]
Hello @IngMiad ,
you can overwrite the URL of the core context via the configuration property  context.defaultUrl (or env var CONTEXT_DEFAULT_URL). An option for your system would be to download the core-context and provide it at an internal reachable endpoint, f.e. via https://github.com/wistefan/context-server. Would that work?

**Comment by IngMiad** [comment]
Hello @wistefan,

thank you for your fast response. It works perfectly - I tested it with a simple httpd webserver (I already had in my project) and just had to add the new configuration property as described. Thank you very much!

Greetings
Inga
