### ISSUE TITLE
Mintaka from sources

### ISSUE THREAD

**Issue by jrobinedwards** [wistefan/mintaka#192]
Hi 
Looks like I'm stuckwith Mintaka. I got the instructions to build it from the docker file (on ubuntu 22.04) and this is the process I followed:

`https://github.com/FIWARE/mintaka/blob/main/docker/Dockerfile

>> Install Java and Maven
sudo apt update
sudo apt install -y openjdk-17-jdk maven

>> Verify installations
java -version
openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment (build 17.0.11+9-Ubuntu-122.04.1)
OpenJDK 64-Bit Server VM (build 17.0.11+9-Ubuntu-122.04.1, mixed mode, sharing)

mvn -version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 17.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8

>> download latest mintaka version
wget https://github.com/FIWARE/mintaka/archive/refs/tags/0.6.6.tar.gz

>> Navigate to project directory
cd /git/mintaka-0.6.6

>> Set project version
mvn versions:set -DnewVersion=0.6.6

>> Build project
mvn clean install -DskipTests

>> Navigate to target directory
cd target

>> Run the JAR file
java -jar mintaka-0.6.6.jar -datasources.default.username *****  -datasources.default.password *****`

Now I get the error:
`~/git/mintaka-0.6.6/target$ java -jar mintaka-0.6.6.jar -datasources.default.username ***** -datasources.default.password *****
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/admin/git/mintaka-0.6.6/target/mintaka-0.6.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/admin/git/mintaka-0.6.6/target/lib/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.6.3)

08:04:41.213 [main] WARN  i.m.context.DefaultBeanContext - The bean created event listener io.micronaut.transaction.jdbc.TransactionAwareDataSource will not be executed because one or more other bean created event listeners inject javax.sql.DataSource:
    org.fiware.mintaka.persistence.tenancy.JpaConfigurationCreatedEventListener --> org.fiware.mintaka.persistence.tenancy.MultiTenantDatasourceConnectionProviderImpl --> javax.sql.DataSource
Change at least one point in the path to be lazy initialized by injecting a provider to avoid this issue
08:04:44.474 [main] WARN  o.h.t.d.j.JavaTypeDescriptorRegistry - HHH000481: Encountered Java type [class java.lang.Object] for which we could not locate a JavaTypeDescriptor and which does not appear to implement equals and/or hashCode.  This can lead to significant performance problems when performing equality/dirty checking involving this Java type.  Consider registering a custom JavaTypeDescriptor or at least implementing equals/hashCode.
08:04:44.489 [main] WARN  o.h.t.d.j.JavaTypeDescriptorRegistry - HHH000481: Encountered Java type [class java.lang.Object] for which we could not locate a JavaTypeDescriptor and which does not appear to implement equals and/or hashCode.  This can lead to significant performance problems when performing equality/dirty checking involving this Java type.  Consider registering a custom JavaTypeDescriptor or at least implementing equals/hashCode.
08:04:46.235 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [org.fiware.mintaka.context.$LdContextCache$Definition$Intercepted] could not be loaded: Error instantiating bean of type  [org.fiware.mintaka.context.$LdContextCache$Definition$Intercepted]

Message: Multiple possible bean candidates found: [io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry]
Path Taken: new $LdContextCache$Definition$Intercepted(ContextProperties contextProperties,BeanResolutionContext $beanResolutionContext,BeanContext $beanContext,Qualifier $qualifier,List $interceptors)
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [org.fiware.mintaka.context.$LdContextCache$Definition$Intercepted] could not be loaded: Error instantiating bean of type  [org.fiware.mintaka.context.$LdContextCache$Definition$Intercepted]

Message: Multiple possible bean candidates found: [io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry]
Path Taken: new $LdContextCache$Definition$Intercepted(ContextProperties contextProperties,BeanResolutionContext $beanResolutionContext,BeanContext $beanContext,Qualifier $qualifier,List $interceptors)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1921)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:245)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3326)
	at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3684)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:341)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:190)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:75)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:323)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:309)
	at org.fiware.mintaka.Application.main(Application.java:29)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [org.fiware.mintaka.context.$LdContextCache$Definition$Intercepted]

Message: Multiple possible bean candidates found: [io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry]
Path Taken: new $LdContextCache$Definition$Intercepted(ContextProperties contextProperties,BeanResolutionContext $beanResolutionContext,BeanContext $beanContext,Qualifier $qualifier,List $interceptors)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2367)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2746)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1915)
	... 9 common frames omitted
Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry]
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2472)
	at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:484)
	at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:3249)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:3140)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:3058)
	at io.micronaut.context.DefaultBeanContext.findBeanDefinition(DefaultBeanContext.java:788)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2790)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:867)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:859)
	at io.micronaut.aop.chain.InterceptorChain.resolveInterceptors(InterceptorChain.java:205)
	at io.micronaut.aop.chain.InterceptorChain.resolveAroundInterceptors(InterceptorChain.java:125)
	at org.fiware.mintaka.context.$LdContextCache$Definition$Intercepted.<init>(Unknown Source)
	at org.fiware.mintaka.context.$LdContextCache$Definition$Intercepted$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354)
	... 16 common frames omitted
`

Note: when I was compiling the project, I set the mvn version to `mvn versions:set -DnewVersion=0.0.1` by mistake as I copied that from the docker file. However, I then changed it to `mvn versions:set -DnewVersion=0.6.6` as that was the mintaka version I downloaded - would this have caused an issue?

_Originally posted by @jrobinedwards in https://github.com/FIWARE/context.Orion-LD/issues/1620#issuecomment-2185887566_

**Comment by jrobinedwards** [comment]
I noticed that the working directory for executing the .jar should be /usr/src not /usr/src/target. 
This is now resolved.
